"""add_product_type_and_bom_fields

Revision ID: 316082cc10c2
Revises: 4e4c1da8a7e0
Create Date: 2026-02-19 20:41:47.893234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316082cc10c2'
down_revision: Union[str, Sequence[str], None] = '4e4c1da8a7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills_of_materials', sa.Column('bom_type', sa.String(), server_default='production', nullable=False))
    op.add_column('bom_items', sa.Column('item_type', sa.String(), server_default='input', nullable=False))
    op.add_column('products', sa.Column('product_type', sa.String(), server_default='Raw', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    op.drop_column('bom_items', 'item_type')
    op.drop_column('bills_of_materials', 'bom_type')
    # ### end Alembic commands ###
