"""add_bom_production_mode

Revision ID: 4e4c1da8a7e0
Revises: b6de9f186673
Create Date: 2026-02-18 11:51:46.729141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4c1da8a7e0'
down_revision: Union[str, Sequence[str], None] = 'b6de9f186673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills_of_materials', sa.Column('production_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills_of_materials', 'production_mode')
    # ### end Alembic commands ###
