"""fix_user_current_branch_id_on_delete

Revision ID: b6de9f186673
Revises: 
Create Date: 2026-02-18 11:03:06.307585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6de9f186673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_current_branch_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'branches', ['current_branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_current_branch_id_fkey'), 'users', 'branches', ['current_branch_id'], ['id'])
    # ### end Alembic commands ###
